apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: th7obkdgs-python 
  janus-idp.io/tekton: th7obkdgs-python
  backstage.io/kubernetes-id: th7obkdgs-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: th7obkdgs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml